return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 66,
  height = 98,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 15,
  nextobjectid = 96,
  properties = {},
  tilesets = {
    {
      name = "Tileset",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "../../Sprites/Tileset.png",
      imagewidth = 256,
      imageheight = 256,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 256,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 1,
      name = "Background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0LENADAMwzD3/6cz5YBuBkIBeoCJtnd8Dhw4cODAgQMHDhw4cODAgQMHDhw4cODAoWEOHDhw4MCBAwcOHDhw4MCBAwcOHDhw4MChYQ4cOHDgwIEDBw4cOHDgwIEDBw4cOHDgwKFhDhw4cODAgQMHDhw4cODAgQMHDhw4cODAoWEOHDhw4MCBw7+DkgGcIxgB"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 2,
      name = "GroundLayer",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztnEtOwzAQhn0HViwpD7FNSJFYgigL4ATACYBD5Oi1O7U6tZynx46T/L/0iUeJM/1wIJlY2SqltgAAAAAAAAAAAIjCDhx4VEil4MEEHijwQIEHCjxQjIeHqYvIIIWCBxN4oMADBR4o8EAZ4uFd86H5jFfOJLnSlKq/hy/Nt+YnWkXTxMwFc91tPFz04Ffzp/nv+fMukpEcz3owc2KjVO3jVr/WRtN2Lnru1YKlH+byJgBeD/egP9bSlIxC2ENxqnsURWIP9vM1e9hG9hDSi5zKQyXsoQr0UMEDPMADPMDDKA+x7xW9SUqg8epdALwe62HtfVp4oMADBR4o8ECZyoN0TyY0U3iw/ZNroXEksOcUKT3wXmDoOCUj5Jxq7h5s/fAgyxw9hF5fwAM8dJHy/iY8UOCBAg/n9a/Jg+86IoYHqfOo431ecXzXEDl7MKTqSVZq2JqLlB5Snj/Aw6l+eIAHXj88wAOvHx7m70Gqx5zzeZTrwfSC3fWBdz3ru/Fsy7H7zNGDW5Ov99f32Ol7/QMP8/Hgey9r8cD/Dr6q8es4fNtycvZgCL3PNrT+XD2k6knN0cPlEf512+tN3+OJ0Z+M5eFJgKbk7sEQozfn9udy95BqzWDOHlJfZ8GDnAfc9z8fBx7ggY+Tq4eu9XBSa/Ry92DXsTX9vuGBYv9frN3DEuYDX8Padvwv3cOz5kV1v8+le+A1LNWD+4wLcwy0zf2lenCfcdH1XpfqgT/jwu4ntof7DtoSw4PBebZFNJr2OZQYDgCxB89yHBQ="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 4,
      name = "Moss and Hazzards",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2kFOg0AAQFEWeoN6B4/p0UvzNZLW6EKEQd5LWLadfJiBTJkmAAAAAAAAAEb3PE1vT/Ox9zj29jI3uOigwzsdokN0iA7RITpEh+gQHaJDdIgO0SE6RIfosJ/lXuB8Dm7n4pSW16AOn3NRB9eDDjp80CE6RIfo8EiH6BAdokN0iA7RITpEh+gQHTJ6h63eLx29w1b/a+iQ0TtsRYeM2mFeG29r5GZG7bD1uM7c4Qj7k/fjel3pWDpChy2s1eHo727o8EiHXH7x2aN3uJ8Xa3zPEemQs3RY7l189Zy+1vhH7/DTfVGHv/udEekQ8yI6RIdYH6JD1u7w3f7OyB34H65Bulzf"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 5,
      name = "Entities_Placeholders",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2jsKwkAUhlEL3YGWugBfe/Gx/7U48DcWghbRe9Vz4EJIIBm+cjKzGQAAAAAAAADUWY/ZVC+igcOYY/Ui4A3mYxbVi2hgOWZVvYgGdAgdQofQIXQIHUKH0CF0CB1Ch/+ynfh9lzHXB/d3Y/YTfwsAAAAA+G3dzsNUncHrsG9/v/dbdQavQ4cOdAgdQofQIXQIHUKHev6RA8DnTX0WDgCA73Uac35w/ezZK8+hsxtz2gq+"
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Ladders",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 301.75,
          y = 1376.38,
          width = 2.25,
          height = 159.443,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1376,
          width = 2.90909,
          height = 159.818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 429.455,
          y = 1440.36,
          width = 2.54545,
          height = 47.2727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 428.909,
          y = 1328.36,
          width = 2.90909,
          height = 79.4545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 429.273,
          y = 1232.55,
          width = 2.54545,
          height = 63.2727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 31.75,
          y = 1200.13,
          width = 3.375,
          height = 63.625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 61.125,
          y = 1120,
          width = 2.75,
          height = 48.125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 429,
          y = 768.5,
          width = 2.75,
          height = 159.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 768,
          width = 4.25,
          height = 544.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 717,
          y = 1264.25,
          width = 3,
          height = 256.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1021.33,
          y = 448,
          width = 3,
          height = 304,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "ThickWalls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1488,
          width = 32,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1296,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1536,
          width = 1055.67,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1440,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1472,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 1376,
          width = 48,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1264,
          width = 400,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1200,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 992,
          width = 16,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 960,
          width = 368,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 672,
          width = 16,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 496,
          width = 416,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 208,
          width = 1056,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 256,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 448,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 768,
          width = 336,
          height = 768,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 496,
          width = 272,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 768,
          width = 48,
          height = 768,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 1120,
          width = 128,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1120,
          width = 96,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "Entities",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 36,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 112.25,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 159.75,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 224.125,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 269.625,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 352,
          y = 1520.13,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 399.75,
          y = 1520,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 65.3333,
          y = 1103.33,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 784,
          y = 751.667,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "Apple",
          type = "Apple",
          shape = "ellipse",
          x = 321.167,
          y = 1361.17,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Apple",
          type = "Apple",
          shape = "ellipse",
          x = 464.667,
          y = 753.167,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "Cricket",
          type = "Cricket",
          shape = "rectangle",
          x = 41.3333,
          y = 1254.33,
          width = 14.3333,
          height = 9.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "Cricket",
          type = "Cricket",
          shape = "rectangle",
          x = 888.833,
          y = 758.333,
          width = 14.3333,
          height = 9.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Cauldron",
          type = "Cauldron",
          shape = "rectangle",
          x = 113.333,
          y = 1088,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "Cauldron",
          type = "Cauldron",
          shape = "rectangle",
          x = 832,
          y = 464,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "Walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 1232,
          width = 32,
          height = 6.72727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1232,
          width = 16,
          height = 6.54545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1232,
          width = 32,
          height = 6.72727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 1232,
          width = 32,
          height = 6.18182,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "Hazards",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80.5,
          y = 1253.25,
          width = 287.25,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480.25,
          y = 1527.5,
          width = 239.5,
          height = 8.75,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "Vines",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 76,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.837,
          y = 1133.28,
          width = 6,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.859,
          y = 1149.27,
          width = 6.08696,
          height = 15.0444,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.925,
          y = 1165.28,
          width = 6,
          height = 15.0222,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.925,
          y = 1181.3,
          width = 5.99807,
          height = 14.9778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.881,
          y = 1197.35,
          width = 6.04348,
          height = 14.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 607.674,
          y = 1130.03,
          width = 2.625,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.902,
          y = 1213.15,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.932,
          y = 1229.03,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 606.119,
          y = 1245.4,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.313,
          y = 539.081,
          width = 2.6,
          height = 1.17778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.013,
          y = 543.367,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 601.888,
          y = 566.117,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.138,
          y = 589.367,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.263,
          y = 609.992,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.263,
          y = 632.117,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.138,
          y = 654.117,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.263,
          y = 676.492,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.388,
          y = 697.367,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 602.513,
          y = 719.492,
          width = 2.6,
          height = 19.4278,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "creditsDoor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 490.091,
          width = 16.0909,
          height = 5.81818,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
