return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 66,
  height = 98,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 16,
  nextobjectid = 131,
  properties = {},
  tilesets = {
    {
      name = "Tileset",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "../../Sprites/Tileset.png",
      imagewidth = 256,
      imageheight = 256,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 256,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 1,
      name = "Background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0LENADAMwzD3/6cz5YBuBkIBeoCJtnd8Dhw4cODAgQMHDhw4cODAgQMHDhw4cODAoWEOHDhw4MCBAwcOHDhw4MCBAwcOHDhw4MChYQ4cOHDgwIEDBw4cOHDgwIEDBw4cOHDgwKFhDhw4cODAgQMHDhw4cODAgQMHDhw4cODAoWEOHDhw4MCBw7+DkgGcIxgB"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 2,
      name = "GroundLayer",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztnEtOwzAQhn0HViwpD7FNSJBYgigL4ATACYBD5Oi1O7U6tZxXPXac5P+lTzxKnOlHAvHESq2UqgEAAAAAAAAAABCFLdjzqJBKwYMJPFDggQIPFHigGA8PUxeRQQoFDybwQIEHCjxQ4IEyxsO75kPzGa+cSXKlKdVwD1+ab81PtIqmiTkWzLzbeLgYwK/mT/M/8OddJCM5nvVgjomNUo2PW/1aF23buehjrxEsfX8sbwLg9XAP+mMjTckohD0Ux7rPokjswX6+Zg91ZA8hvcipPEhfo1SBHip4gAd4yMYD3y885O8h9r2iN0kJNF6zDYDXYz2svU8LDxR4oMADBR4oU3mQ7smEZgoPtn9yLTSOBPaaIqUH3gsMHadkhFxTzd2DrR8eZJmjh9D5BTzAQx8p72/CAwUeKPBwWv+aPPjmETE8SF1HHe7ziuObQ+TswZCqJ1mpcWsuUnpIef0AD8f64QEeeP3wAA+8fniYvwepHnPO11GuB9MLdtcH3g2s78azLcfuM0cPbk2+3t/Qc2fo/Ace5uPB917W4oH/HXxV56/j8G3LydmDIfQ+29j6c/WQqic1Rw+XB/jXXa+3fY8nRn8ylocnAdqSuwdDjN6c25/L3UOqNYM5e0g9z4IHOQ+47386DjzAAx8nVw996+Gk1ujl7sGuY2v7fcMDxf6/WLuHJRwPfA1r1/m/dA/PmhfV/z6X7oHXsFQP7jMuzDnQdewv1YP7jIu+97pUD/wZF3Y/sT3c99CVGB4MzrMtotG2z7HEcACIHcHhGhA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 4,
      name = "Moss and Hazzards",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2kGOgkAURVEGugPcQy/TpYt5EwKd7gFl8UvOSRgqlZsC8es0AQAAAAAAAFDdfZqet+U4ex1neywNZh26d1j23nsPltO7w5xzlqND6BA6hA6hQ+gQnqNCh9AhdAgdQofQIXQIHc6zngUeeb4cfaa43oNHOoy+l7fr18F+aNFhdDqEDqFD6BA67OkQOsSVO7g/hA57OoQOoUPoEDqEDlG9Q69ZcPUOvWZ/OkT1Dr3oEFU79P7/c9UOvdd15Q4jfO/eruun0bE2Qoce/L4ZOuzpEPOB147eYXtdtHifEekQV+mwnl389pzeav3VO/z3uajD585TkQ7huggdQodwfwgdonWHv+Y7lTvwHV75c2Td"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 5,
      name = "Entities_Placeholders",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2jsKwkAUhlEL3YGWugBfe/Gx/7U48DcWghbRe9Vz4EJIIBm+cjKzGQAAAAAAAADUWY/ZVC+igcOYY/Ui4A3mYxbVi2hgOWZVvYgGdAgdQofQIXQIHUKH0CF0CB1Ch/+ynfh9lzHXB/d3Y/YTfwsAAAAA+G3dzsNUncHrsG9/v/dbdQavQ4cOdAgdQofQIXQIHUKHev6RA8DnTX0WDgCA73Uac35w/ezZK8+hsxtz2gq+"
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Ladders",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 301.75,
          y = 1376.38,
          width = 2.25,
          height = 159.443,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1376,
          width = 2.90909,
          height = 159.818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 429.455,
          y = 1440.36,
          width = 2.54545,
          height = 47.2727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 428.909,
          y = 1328.36,
          width = 2.90909,
          height = 79.4545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 429.273,
          y = 1232.55,
          width = 2.54545,
          height = 63.2727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 31.75,
          y = 1200.13,
          width = 3.375,
          height = 63.625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 61.125,
          y = 1120,
          width = 2.75,
          height = 48.125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 429,
          y = 768.5,
          width = 2.75,
          height = 159.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 768,
          width = 4.25,
          height = 544.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 717,
          y = 1264.25,
          width = 3,
          height = 256.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1021.33,
          y = 448,
          width = 3,
          height = 304,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 428.5,
          y = 976,
          width = 3.5,
          height = 32.125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416.25,
          y = 496,
          width = 3.25,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 716.75,
          y = 768.25,
          width = 3,
          height = 63.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "ThickWalls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1488,
          width = 32,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1296,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1536,
          width = 1055.67,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1440,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1472,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 1376,
          width = 48,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1264,
          width = 400,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1200,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 992,
          width = 16,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 960,
          width = 368,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 672,
          width = 16,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 496,
          width = 416,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 16,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 208,
          width = 1056,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 256,
          width = 16,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 448,
          width = 32,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 768,
          width = 336,
          height = 768,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 496,
          width = 272,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 768,
          width = 48,
          height = 768,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 1120,
          width = 128,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1120,
          width = 96,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "Entities",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 36,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 112.25,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 159.75,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 224.125,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 269.625,
          y = 1519.88,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 352,
          y = 1520.13,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 399.75,
          y = 1520,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 65.3333,
          y = 1103.33,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "Elderberries",
          type = "Elderberries",
          shape = "rectangle",
          x = 784,
          y = 751.667,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "Apple",
          type = "Apple",
          shape = "ellipse",
          x = 321.167,
          y = 1361.17,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Apple",
          type = "Apple",
          shape = "ellipse",
          x = 464.667,
          y = 753.167,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "Cricket",
          type = "Cricket",
          shape = "rectangle",
          x = 41.3333,
          y = 1254.33,
          width = 14.3333,
          height = 9.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "Cricket",
          type = "Cricket",
          shape = "rectangle",
          x = 888.833,
          y = 758.333,
          width = 14.3333,
          height = 9.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Cauldron",
          type = "Cauldron",
          shape = "rectangle",
          x = 113.333,
          y = 1088,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "Cauldron",
          type = "Cauldron",
          shape = "rectangle",
          x = 832,
          y = 464,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "Shadow",
          type = "Shadow",
          shape = "ellipse",
          x = 933.167,
          y = 753.417,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "Poke",
          type = "Poke",
          shape = "ellipse",
          x = 176.667,
          y = 1489.17,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "Poke",
          type = "Poke",
          shape = "ellipse",
          x = 368.917,
          y = 1248.42,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "Poke",
          type = "Poke",
          shape = "ellipse",
          x = 432.167,
          y = 752.167,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "Poke",
          type = "Poke",
          shape = "ellipse",
          x = 1024.17,
          y = 432.167,
          width = 14.6667,
          height = 14.6667,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "Walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 1232,
          width = 32,
          height = 6.72727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1232,
          width = 16,
          height = 6.54545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1232,
          width = 32,
          height = 6.72727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 1232,
          width = 32,
          height = 6.18182,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "Hazards",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80.5,
          y = 1253.25,
          width = 287.25,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480.25,
          y = 1527.5,
          width = 239.5,
          height = 8.75,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "Vines",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 76,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.837,
          y = 1133.28,
          width = 6,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.859,
          y = 1149.27,
          width = 6.08696,
          height = 15.0444,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.925,
          y = 1165.28,
          width = 6,
          height = 15.0222,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.925,
          y = 1181.3,
          width = 5.99807,
          height = 14.9778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.881,
          y = 1197.35,
          width = 6.04348,
          height = 14.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 607.674,
          y = 1130.03,
          width = 2.625,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.902,
          y = 1213.15,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 605.932,
          y = 1229.03,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "Vine2",
          type = "",
          shape = "rectangle",
          x = 606.119,
          y = 1245.4,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.446,
          y = 550.099,
          width = 6,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.468,
          y = 566.092,
          width = 6.08696,
          height = 15.0444,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.534,
          y = 582.099,
          width = 6,
          height = 15.0222,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.534,
          y = 598.121,
          width = 5.99807,
          height = 14.9778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.49,
          y = 614.175,
          width = 6.04348,
          height = 14.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 598.283,
          y = 546.849,
          width = 2.625,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.511,
          y = 629.974,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.512,
          y = 646.235,
          width = 5.99807,
          height = 14.9778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.468,
          y = 662.289,
          width = 6.04348,
          height = 14.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.489,
          y = 678.088,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.411,
          y = 693.743,
          width = 6.08696,
          height = 15.0444,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.477,
          y = 709.75,
          width = 6,
          height = 15.0222,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.477,
          y = 725.772,
          width = 5.99807,
          height = 14.9778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.433,
          y = 741.826,
          width = 6.04348,
          height = 14.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.454,
          y = 757.625,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.455,
          y = 773.886,
          width = 5.99807,
          height = 14.9778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.411,
          y = 789.94,
          width = 6.04348,
          height = 14.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "Vine1",
          type = "",
          shape = "rectangle",
          x = 596.432,
          y = 805.739,
          width = 6.04348,
          height = 15.0625,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "EnemyWalls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 97,
          name = "EnemyWalls",
          type = "EnemyWalls",
          shape = "rectangle",
          x = 1007.88,
          y = 735.5,
          width = 9.75,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "EnemyWalls",
          type = "EnemyWalls",
          shape = "rectangle",
          x = 720.375,
          y = 735.5,
          width = 9.75,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "creditsDoor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 490.091,
          width = 16.0909,
          height = 5.81818,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
