return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 66,
  height = 98,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 7,
  nextobjectid = 1,
  properties = {},
  tilesets = {
    {
      name = "Tileset",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "../../Sprites/Tileset.png",
      imagewidth = 256,
      imageheight = 256,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 256,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 1,
      name = "Background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0LENADAMwzD3/6cz5YBuBkIBeoCJtnd8Dhw4cODAgQMHDhw4cODAgQMHDhw4cODAoWEOHDhw4MCBAwcOHDhw4MCBAwcOHDhw4MChYQ4cOHDgwIEDBw4cOHDgwIEDBw4cOHDgwKFhDhw4cODAgQMHDhw4cODAgQMHDhw4cODAoWEOHDhw4MCBw7+DkgGcIxgB"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 2,
      name = "GroundLayer",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztm8tOwzAQRf0PrFhSHmKbkiKxBFG+K59O3KnFNMqLeuw4zbnSEa8mTA4OxGNzcM4dAAAAAAAAACAJRzjx7kjt8OCDBwkeJHiQ4EHiPbwtXUQBqRwefPAgwYMEDxI8SPDg3EPL3uHBjwU/7/Ye7magM+f1Y8fHxvJ8wYMfEzvnmpS0Y68xLP00lncR6Hq0h/ZtY81eURl7qP7qvooqs4fw/pY9HBJ7iOlFLuWhNvZQR3qo8YAHPOABD1d5SL1W9GMpQc7XHCPQ9QQPW+/T4kGCBwkeJHiQLOXBuicTmyU8hP7Jo9F5LAjPFDk96F5g7Hn2iphnqrV7CPXjwZY1eoidX+ABD1PkXM/CgwQPEjxc1r8lD33ziBQerJ6jzuu85vTNIUr24MnVk6ydzZ6LFB5yPj/g4a9+POBB148HPOj68bB+D1Y95pKfo7oefC/4ucPLzPqeeo7VhO9ZooduTX29v7n3ztz5Dx7W46HvWrbiQf8e/HbX7+PoO1ZTsgdP7Drbf+sv1UOuntQaPdyf0R+PfX3oczop+pOpPHwYMJTSPXhS9Oa6/bnSPeTaM1iyh9zzLDzYeWDd//I8eMCDPk+pHqb2w1nt0SvdQ9jHNvTzxoMk/L3YuodbGA96D+vY/X/rHj5bvtz0dd66B13DVjz4e2Bs7G/Fw9S14sHOw+sEY0nhwZOqBzP0vw6esXWvKVI4AOEXidAZjQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 4,
      name = "Moss and Hazzards",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2kFOg0AAQFEWeoN6B4/p0UvzNZLW6EKEQd5LWLadfJiBTJkmAAAAAAAAAEb3PE1vT/Ox9zj29jI3uOigwzsdokN0iA7RITpEh+gQHaJDdIgO0SE6RIfosJ/lXuB8Dm7n4pSW16AOn3NRB9eDDjp80CE6RIfo8EiH6BAdokN0iA7RITpEh+gQHTJ6h63eLx29w1b/a+iQ0TtsRYeM2mFeG29r5GZG7bD1uM7c4Qj7k/fjel3pWDpChy2s1eHo727o8EiHXH7x2aN3uJ8Xa3zPEemQs3RY7l189Zy+1vhH7/DTfVGHv/udEekQ8yI6RIdYH6JD1u7w3f7OyB34H65Bulzf"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 66,
      height = 98,
      id = 5,
      name = "Entities_Placeholders",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2jsKwkAUhlEL3YGWugBfe/Gx/7U48DcWghbRe9Vz4EJIIBm+cjKzGQAAAAAAAADUWY/ZVC+igcOYY/Ui4A3mYxbVi2hgOWZVvYgGdAgdQofQIXQIHUKH0CF0CB1Ch/+ynfh9lzHXB/d3Y/YTfwsAAAAA+G3dzsNUncHrsG9/v/dbdQavQ4cOdAgdQofQIXQIHUKHev6RA8DnTX0WDgCA73Uac35w/ezZK8+hsxtz2gq+"
    }
  }
}
